// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1WkWxR53kQhBxlJmy9v5YOOiLXpO1_Lo',
    appId: '1:133543848732:web:b2a405bdcfc4e91494e8d9',
    messagingSenderId: '133543848732',
    projectId: 'imacoco-f64b7',
    authDomain: 'imacoco-f64b7.firebaseapp.com',
    storageBucket: 'imacoco-f64b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfDwH4U0_C5UYY-4hEKfSppNKRhwEukN4',
    appId: '1:133543848732:android:8beacca305a9ce5c94e8d9',
    messagingSenderId: '133543848732',
    projectId: 'imacoco-f64b7',
    storageBucket: 'imacoco-f64b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1gksvL4oPM_KB35_AXOMcMLXvM5VAHhc',
    appId: '1:133543848732:ios:83e17f7958fa0a5c94e8d9',
    messagingSenderId: '133543848732',
    projectId: 'imacoco-f64b7',
    storageBucket: 'imacoco-f64b7.firebasestorage.app',
    iosBundleId: 'com.example.imacoco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1gksvL4oPM_KB35_AXOMcMLXvM5VAHhc',
    appId: '1:133543848732:ios:83e17f7958fa0a5c94e8d9',
    messagingSenderId: '133543848732',
    projectId: 'imacoco-f64b7',
    storageBucket: 'imacoco-f64b7.firebasestorage.app',
    iosBundleId: 'com.example.imacoco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1WkWxR53kQhBxlJmy9v5YOOiLXpO1_Lo',
    appId: '1:133543848732:web:b9ec7378abd2e7ff94e8d9',
    messagingSenderId: '133543848732',
    projectId: 'imacoco-f64b7',
    authDomain: 'imacoco-f64b7.firebaseapp.com',
    storageBucket: 'imacoco-f64b7.firebasestorage.app',
  );

}